language: java

jdk: openjdk16

sudo: false

before_install: chmod +x mvnw

install: true

script: ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
    - $HOME/.m2

